services:
  app1:
    build:
      context: .
      dockerfile: App1.Dockerfile
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: app1
    volumes:
      - ./api/app1:/var/www/html:rw